<?php

use BdUser\Entity\User;

$users = $this->users;

/** @var Zend\View\Helper\FlashMessenger $flashMessenger */
$flashMessenger = $this->flashMessenger();

?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Users list') ?></h3>
            </div>
            <div class="panel-body">
                <?php if ($flashMessenger->getPluginFlashMessenger()->hasCurrentSuccessMessages()) { ?>
                    <div class="alert alert-success col-sm-12">
                        <?= $flashMessenger->render('success'); ?>
                    </div>
                <?php } ?>
                <div class="row" style="padding-bottom: 10px">
                    <div class="col-md-12">
                        <a href="<?= $this->url('bd_user_index/default', array('action' => 'new')); ?>" class="btn btn-sm btn-default"><?= $this->translate('Create new') ?></a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><?= $this->translate('Username') ?></th>
                                <th><?= $this->translate('E-mail address') ?></th>
                                <th><?= $this->translate('Full name') ?></th>
                                <th><?= $this->translate('Creation date') ?></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($users && count($users) > 0) { ?>
                                <?php foreach ($users as $user) {
                                    /** @var User $user */
                                    ?>

                                    <tr>
                                        <td><?= $user->getId(); ?></td>
                                        <td><?= $user->getUsername(); ?></td>
                                        <td><?= ($user->getUserDetail() ? $user->getUserDetail()->getEmail() : ''); ?></td>
                                        <td><?= ($user->getUserDetail() ? $user->getUserDetail()->getFullName() : ''); ?></td>
                                        <td><?= $user->getCreationDate(); ?></td>
                                        <td>
                                            <a href="<?= $this->url('bd_user_index/default', array('action' => 'edit', 'id' => $user->getId())); ?>" class="btn btn-sm btn-default"><?= $this->translate('Edit') ?></a>
                                            <a href="<?= $this->url('bd_user_index/default', array('action' => 'confirm', 'id' => $user->getId())); ?>" class="btn btn-sm btn-danger"><?= $this->translate('Remove') ?></a>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <tr>
                                    <td colspan="6" style="text-align: center"><strong><?= $this->translate('No records') ?></strong></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>