<?php

use BdUser\Entity\User;

$user = $this->user;
$form = $this->userForm;
/** @var Zend\Form\Form $form */

$passwordForm = $this->passwordForm;
/** @var Zend\Form\Form $passwordForm */

$userDetails = $this->userDetailForm;
/** @var Zend\Form\Form $userDetails */

$userPhoneForm = $this->userPhoneForm;
/** @var Zend\Form\Form $userPhoneForm */

/** @var Zend\View\Helper\FlashMessenger $flashMessenger */
$flashMessenger = $this->flashMessenger();
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Create user') ?></h3>
            </div>
            <div class="panel-body">
                <?php if ($flashMessenger->getPluginFlashMessenger()->hasCurrentErrorMessages()) { ?>
                    <div class="alert alert-danger col-sm-12">
                        <?= $flashMessenger->render('error'); ?>
                    </div>
                <?php } ?>

                <form action="" method="post">
                    <div class="row" style="padding-bottom: 10px">
                        <div class="col-md-6">
                            <h4><?= $this->translate('User information'); ?></h4>

                            <?php foreach ($form->getElements() as $element) {
                                /** @var Zend\Form\Element $element */
                                ?>
                                <?= $this->formRow($element->setAttribute('class', 'form-control')); ?>
                            <? } ?>

                            <h4><?= $this->translate('Authentication information'); ?></h4>

                            <?php foreach ($passwordForm->getElements() as $element) {
                                /** @var Zend\Form\Element $element */
                                ?>
                                <?= $this->formRow($element->setAttribute('class', 'form-control')); ?>
                            <? } ?>
                        </div>
                        <div class="col-md-6">
                            <h4><?= $this->translate('User details'); ?></h4>
                            <?php foreach ($userDetails->getElements() as $element) {
                                /** @var Zend\Form\Element $element */
                                ?>
                                <?= $this->formRow($element->setAttribute('class', 'form-control')); ?>
                            <? } ?>

                            <h4><?= $this->translate('Phone number'); ?></h4>
                            <?php foreach ($userPhoneForm->getElements() as $element) {
                                /** @var Zend\Form\Element $element */
                                ?>
                                <?= $this->formRow($element->setAttribute('class', 'form-control')); ?>
                                <?php
                                    echo $this->FormElementErrors($element);
                                ?>
                            <? } ?>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px">
                        <div class="col-md-12">
                            <a href="<?= $this->url('bd_user_index'); ?>" class="btn btn-sm btn-default pull-left"><?= $this->translate('Back to list') ?></a>
                            <button class="btn btn-primary pull-right" type="submit"><span><?= $this->translate('Save'); ?></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>